language: ruby
rvm:
  - ruby-head
  - mruby-head
  - jruby-head
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1
  - rbx-2.2.6
  - rbx-2.2.2
  
